
#### Data

This data shows the calories in various fast food items across different famous joints along with the nutritional breakdown like calories, protein, fats, cholesterol, sugar etc in those items.
The data source is from *Fast Food Nutrition* 
(fastfoodnutrition.com)



#### Purpose

The purpose of the app is to:  
Make a consumer aware of how healthy or unhealthy fast food is so that they become aware of what goes in the food they eat. This is done interactively in three ways:  

1. make a user understand and aware of how each restaurant fares in terms of total fat and calories in their items.  
2. show how much protein distribution these items have, 
3. show the user the foods with highest cholesterol level so that they are aware of the same. 

As expected, fast food data is high in calories , fat and cholesterol content.However, even a healthy approach is taken and the protein content is checked for in these items. The app uses interactive components to see how the choices that a consumer makes effect the visibility of these nutrients.

#### Creator

Sanna Meer (smee0005@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
